#!/usr/bin/env bash

public_ip=$( terraform output -json tfinstance1_ip | jq -r '.[0]' )

echo "Instance public ip:" ${public_ip}

ssh -i ../ssh-keys/id_rsa_aws \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    admin@${public_ip}
